version: '3.8'

services:
  explain-recommendations:
    image: tpphu/explain-recommendations:latest
    container_name: explain-recommendations-container
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      jupyter lab --notebook-dir=/workspace --ip=0.0.0.0 --port=8888 --no-browser --allow-root